version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/myapp
      - bundle-data:/usr/local/bundle
    depends_on:
      - db
    ports:
      - "3000:3000"
    command: tail -f /dev/null
  db:
    image: postgres:9.6
    volumes:
      - pgsql-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
volumes:
  pgsql-data:
    driver: local
  bundle-data:
    driver: local